GET http://localhost:3003/api/blogs

### 
GET http://localhost:3003/api/blogs/62f96eac7d211a54843e7475

###
POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imx1aXNzZGV2IiwiaWQiOiI2MmY5NTI2ZWIzNTk4NDgxYTM5NTQ5MzIiLCJpYXQiOjE2NjA1MjQ0NDJ9.yq_0J6tcYfbGcikoHlekEyAtRPhanJbeHZvJDeKGjxo

{
  "title": "Linux is awesome",
  "author": "Luis Sanchez",
  "url": "http://luissresources.com",
  "likes": 10,
  "user": "62f9526eb3598481a3954932"
}

###
DELETE http://localhost:3003/api/blogs/62f956d0f434825b3a696770
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imx1aXNzZGV2IiwiaWQiOiI2MmY5NTI2ZWIzNTk4NDgxYTM5NTQ5MzIiLCJpYXQiOjE2NjA1MjQ0NDJ9.yq_0J6tcYfbGcikoHlekEyAtRPhanJbeHZvJDeKGjxo

###
GET http://localhost:3003/api/users

### 
GET http://localhost:3003/api/users/62f88b7cc3a0bdfd53241af8

###
POST http://localhost:3003/api/users HTTP/1.1
Content-Type: application/json

{
  "username": "family",
  "name": "family@gmail.com",
  "password": "letsgofamily"
}

###
DELETE http://localhost:3003/api/users/62f96f1779441f31dd078838
###
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "luissdev",
  "password": "letsgo"
}