GET http://localhost:3003/api/blogs

### 
GET http://localhost:3003/api/blogs/62ec5b2a841a969389e7bbd5

###
POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json

{
  "title": "JS is awesome",
  "author": "Luis Sanchez",
  "url": "luissresources.com",
  "likes": 10,
  "user": "62f7fb9e4e8fc0616ba131cf"
}

###
DELETE http://localhost:3003/api/blogs/62f7f6e410a887858872a490

###
GET http://localhost:3003/api/users

### 
GET http://localhost:3003/api/users/62ec5b2a841a969389e7bbd5

###
POST http://localhost:3003/api/users HTTP/1.1
Content-Type: application/json

{
  "username": "luissdev",
  "name": "Luis Sanchez",
  "password": "vamospalante"
}

###
DELETE http://localhost:3003/api/users/62f7e93a628a9304cc51a1eb